[build]
  command = "# no build needed"
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["wordlist.txt"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
